### ISSUE TITLE
Uses for DiffEngine

### ISSUE THREAD

**Issue by jzabroski** [SimonCropp/DiffEngine#1]
#### Is the feature request related to a problem

Yes - As part of RazorLight, I want to figure out the best way to compare a snapshot of a Razor compiler output to the latest output.  Rob D. Moore of MRCollective suggested this is called "approval testing", and that Shoudly and ApprovalTests.Net both support launching a file diff tool. DiffEngine seems like it could be useful here.

#### Describe the solution

Let's discuss what you're building this project for and whether it makes sense to adopt an ecosystem around DiffEngine.

#### Describe alternatives considered

Use ApprovalTests.Net or Shoudly.

#### Additional context

https://github.com/toddams/RazorLight/pull/309#issuecomment-612625943

**Comment by SimonCropp** [comment]
updated readme 
![image](https://user-images.githubusercontent.com/122666/79175971-70955e80-7e42-11ea-89ce-120ec62f59ce.png)


and send a PR to razorlight. 

and discussed with @jzabroski on a call. 

will close this for now. please ping back if u think it needs more clarification
